#ifndef AWNING_RFM69_DEFAULT_CONFIG_H
#define AWNING_RFM69_DEFAULT_CONFIG_H

#ifdef RFM69_DEFAULT_CONFIG_INCLUDE
#include RFM69_DEFAULT_CONFIG_INCLUDE
#else

#define RFM69_DEFAULT_SPI spi0
#define RFM69_DEFAULT_SPI_MOSI 3
#define RFM69_DEFAULT_SPI_MISO 4
#define RFM69_DEFAULT_SPI_SCK 2
#define RFM69_DEFAULT_SPI_CS 5
#define RFM69_DEFAULT_RESET 9

#endif

#endif